### ISSUE TITLE
html format mails

### ISSUE THREAD

**Issue by nixmomo** [jfqd/redmine_helpdesk#80] opened 2015-05-14 21:08 UTC
Hi,
i have a new "issue".
The Mails from helpdesk are not in html format.... all other mails from redmine have a correct html format.

is there a easy solution to fix this or send html mails with helpdesk?

**Comment by vilppuvuorinen** [comment] 2015-05-15 03:44
There are only solutions that require some manual labor. However, I also want to have html formattable mail. Unless someone else steps in before that I'm going to provide a pull request during the summer about this.

Does @jfqd have an opinion about this?

**Comment by jfqd** [comment] 2015-05-15 06:36
Duplicate of https://github.com/jfqd/redmine_helpdesk/issues/33.

**Comment by nixmomo** [comment] 2015-05-15 17:30
And a Solution is what? 

The Mails are all send with the html tags ... this tags make the text very "unreadable"
The best is when a) the html tags deleted or b) the mail send as html

**Closed** 2021-12-23 08:00 UTC
